### ISSUE TITLE
Update Readme to include APPID 

### ISSUE THREAD

**Issue by debonair** [mstahv/consuming-rest-apis#2]
the api you are consuming requires the user to signup for an API key and use this key  to set the APPID param in the request please, I can make a pull request if you like.

**Comment by mstahv** [comment]
Did you upgrade the example with API key? If you did or have some time to do it, please make a pull request, I'd love to get the fix in!

The best option would probably to make rewrite the example so that it wouldn't depend on services that need API key. Do you happen to have any suggestions of such services?

**Comment by mstahv** [comment]
I opened the project and updated it to use appid (aka API key).
